gitlab:
  image: gitlab/gitlab-ce:latest
  restart: always
  hostname: 'git.project-r.construction'
  environment:
    GITLAB_OMNIBUS_CONFIG: >
      external_url 'https://git.project-r.construction';
      nginx['redirect_http_to_https'] = true;
      nginx['ssl_certificate'] = "/etc/letsencrypt/live/git.project-r.construction/fullchain.pem";
      nginx['ssl_certificate_key'] = "/etc/letsencrypt/live/git.project-r.construction/privkey.pem";
      registry_external_url 'https://registry.git.project-r.construction';
      registry_nginx['ssl_certificate'] = "/etc/letsencrypt/live/git.project-r.construction/fullchain.pem";
      registry_nginx['ssl_certificate_key'] = "/etc/letsencrypt/live/git.project-r.construction/privkey.pem";
      gitlab_rails['gitlab_shell_ssh_port'] = 8022;
      gitlab_rails['smtp_enable'] = true;
      gitlab_rails['smtp_address'] = "smtp.mailgun.org";
      gitlab_rails['smtp_port'] = 587;
      gitlab_rails['smtp_authentication'] = "plain";
      gitlab_rails['smtp_enable_starttls_auto'] = true;
      gitlab_rails['smtp_user_name'] = "git@project-r.construction";
      gitlab_rails['smtp_password'] = "SECRET";
      gitlab_rails['smtp_domain'] = "project-r.construction";
  ports:
    - '80:80'
    - '443:443'
    - '8022:22'
  volumes:
    - /docker/data/gitlab/config:/etc/gitlab
    - /docker/data/gitlab/logs:/var/log/gitlab
    - /docker/data/gitlab/data:/var/opt/gitlab
    - /etc/letsencrypt/:/etc/letsencrypt:ro
